steps:
  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ndns-go-cloudrun', '-f', 'Dockerfile.cloudrun', '.']

  # 이미지를 Container Registry에 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ndns-go-cloudrun']

  # Cloud Run에 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'ndns-go-cloudrun'
      - '--image'
      - 'gcr.io/$PROJECT_ID/ndns-go-cloudrun'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--port'
      - '8085'
      - '--set-secrets=WORKER_URL=WORKER_URL:latest,APP_NAME=APP_NAME:latest,APP_URL=APP_URL:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest,AWS_REGION=AWS_REGION:latest,NAVER_CLIENT_ID=NAVER_CLIENT_ID:latest,NAVER_CLIENT_SECRET=NAVER_CLIENT_SECRET:latest'
      - '--timeout'
      - '300s'
      - '--min-instances'
      - '1'

images:
  - 'gcr.io/$PROJECT_ID/ndns-go-cloudrun'