# 빌드 스테이지
FROM golang:1.21-alpine AS builder

WORKDIR /app

# 필요한 빌드 도구 설치
RUN apk add --no-cache git

# 의존성 파일 복사 및 다운로드
COPY go.mod go.sum ./
RUN go mod download

# 소스 코드 복사
COPY . .

# Cloud Run 바이너리 빌드
RUN CGO_ENABLED=0 GOOS=linux go build -o /cloudrun ./cmd/cloudrun/main.go

# 실행 스테이지
FROM alpine:latest

WORKDIR /app

# 타임존 설정
RUN apk add --no-cache tzdata
ENV TZ=Asia/Seoul

# 실행 파일 복사
COPY --from=builder /cloudrun .

# 환경 변수 설정
ENV PORT=8080
ENV APP_ENV=prod

# 실행
CMD ["./cloudrun"] 