global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ndns-go'
    metrics_path: /metrics
    static_configs:
      # 도커 내 서비스에 직접 접근 (localhost 사용)
      - targets: ['host.docker.internal:8085']
      # 아래는 다양한 환경에 따른 설정 예시입니다
      # 로컬 개발: host.docker.internal:8085  
      # 운영 환경 (외부): api.ndns.site:8085
      # 운영 환경 (내부): [서버 내부 IP]:8085
    # Kubernetes 환경을 위한 설정 (주석 처리됨)
    # kubernetes_sd_configs:
    #  - role: pod
    #    namespaces:
    #      names:
    #        - default
    # relabel_configs:
    #  - source_labels: [__meta_kubernetes_pod_label_app]
    #    regex: ndns-go
    #    action: keep
    #  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    #    regex: 'true'
    #    action: keep

  # 시스템 메트릭 수집을 위한 Node Exporter 설정 (선택 사항)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] 