# 프로메테우스 메인 설정 파일
# 이 파일은 프로메테우스가 메트릭을 수집할 대상을 정의합니다.
# Dockerfile.prometheus에서 이 파일을 /etc/prometheus/prometheus.yml로 복사합니다.

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ndns-go'
    metrics_path: /metrics
    static_configs:
      # API 서버 컨테이너 이름으로 접근 (Docker 네트워크 내에서)
      - targets: ['api-server:8085']
      # 백업 타겟으로 localhost 유지
      - targets: ['localhost:8085']
      # 아래는 다양한 환경에 따른 설정 예시입니다
      # 로컬 개발: host.docker.internal:8085  
      # 운영 환경 (외부): api.ndns.site:8085
      # 운영 환경 (내부): [서버 내부 IP]:8085
    # Kubernetes 환경을 위한 설정 (주석 처리됨)
    # kubernetes_sd_configs:
    #  - role: pod
    #    namespaces:
    #      names:
    #        - default
    # relabel_configs:
    #  - source_labels: [__meta_kubernetes_pod_label_app]
    #    regex: ndns-go
    #    action: keep
    #  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    #    regex: 'true'
    #    action: keep

  # 시스템 메트릭 수집을 위한 Node Exporter 설정 (선택 사항)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100'] 