# 프로메테우스 메인 설정 파일
# 이 파일은 프로메테우스가 메트릭을 수집할 대상을 정의합니다.
# Dockerfile.prometheus에서 이 파일을 /etc/prometheus/prometheus.yml로 복사합니다.

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ndns-go'
    metrics_path: /metrics
    static_configs:
      - targets: ['ndns-go:8085']
