version: '3.8'

services:
  prometheus:
    image: sh5080/ndns-prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitoring
    volumes:
      - prometheus_data:/prometheus

  grafana:
    image: sh5080/ndns-grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - monitoring
    volumes:
      - grafana_data:/var/lib/grafana

networks:
  monitoring:

volumes:
  prometheus_data:
  grafana_data:
