name: Docker Pull & Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ndns-go:latest
            chmod +x deploy/deploy.sh
            ./deploy/deploy.sh

      - name: Notify Discord on Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ✅ **ndns-go 배포 완료**
          description: |
            - 브랜치: `${{ github.ref_name }}`
            - 커밋: `${{ github.sha }}`
            - 시간: `${{ github.event.head_commit.timestamp }}`
