name: Docker Pull & Deploy

on:
  workflow_run:
    workflows: ["Docker Build and Push"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get public IP from EC2 tag
        id: get_ip
        run: |
          IP=$(aws ec2 describe-instances \
            --region ap-northeast-2 \
            --filters "Name=tag:Name,Values=ndns-go" "Name=instance-state-name,Values=running" \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text)
          echo "PUBLIC_IP=$IP" >> $GITHUB_OUTPUT

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ steps.get_ip.outputs.PUBLIC_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/ndns-go:latest
            chmod +x deploy/deploy.sh
            ./deploy/deploy.sh

      - name: Notify Discord on Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ✅ **ndns-go 배포 완료**
          description: |
            - 브랜치: `${{ github.ref_name }}`
            - 커밋: `${{ github.sha }}`
            - 시간: `${{ github.event.head_commit.timestamp }}`
